apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: janny
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - watch
  - list
  - delete
