apiVersion: apps/v1
kind: Deployment
metadata:
  name: janny
  labels:
    app: janny
spec:
  selector:
    matchLabels:
      app: janny
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: janny
    spec:
      serviceAccountName: janny
      containers:
        - name: janny
          image: janny:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--included-resources"
            - "deployments,configmaps,pods"
            - "--namespaces"
            - "default"
